#!/bin/bash
 #===============================================================================
 #
 #          FILE:  MapReduce 
 #
 #         USAGE:  ---
 #
 #   DESCRIPTION:  ---
 #
 #       OPTIONS:  ---
 #  REQUIREMENTS:  ---
 #          BUGS:  ---
 #         NOTES:  ---
 #        AUTHOR:  IC (Yin-Chi Peng), <psycsieic@gmail.com>
 #       COMPANY:  ---
 #       VERSION:  1.0
 #       CREATED:  2015-05-11 16:40:27
 #      REVISION:  ---
 #      MODIFIED:
 #
 #===============================================================================

if [ $# -eq 1 ]
then

./MapReduce_Stage1
./MapReduce_Stage2 $1

else
echo "./MapReduce [search_target]"
fi 
