#!/bin/bash
 #===============================================================================
 #
 #          FILE:  ST_Mapper_s1_output 
 #
 #         USAGE:  ---
 #
 #   DESCRIPTION:  ---
 #
 #       OPTIONS:  ---
 #  REQUIREMENTS:  ---
 #          BUGS:  ---
 #         NOTES:  ---
 #        AUTHOR:  IC (Yin-Chi Peng), <psycsieic@gmail.com>
 #       COMPANY:  ---
 #       VERSION:  1.0
 #       CREATED:  2015-05-11 16:40:27
 #      REVISION:  ---
 #      MODIFIED:
 #
 #===============================================================================


STREAMJAR=/usr/local/hadoop/share/hadoop/tools/lib/hadoop-streaming-2.2.0.jar
#INPUT=/testinput
INPUT1=/shop1
INPUT2=/shop2
INPUT3=/shop3
INPUT4=/shop4
INPUT5=/shop5
Small_Test_Input1=./Small_Test/shop1
Small_Test_Input2=./Small_Test/shop2
Small_Test_Input3=./Small_Test/shop3
Small_Test_Input4=./Small_Test/shop4
Small_Test_Input5=./Small_Test/shop5
OUTPUT=mapper_s1_output
OUTPUT_DIRECTORY=result

MAPPER=mapper_s1
REDUCER=cat

hadoop fs -rm $INPUT1 $INPUT2 $INPUT3 $INPUT4 $INPUT5

hadoop fs -put $Small_Test_Input1 /
hadoop fs -put $Small_Test_Input2 /
hadoop fs -put $Small_Test_Input3 /
hadoop fs -put $Small_Test_Input4 /
hadoop fs -put $Small_Test_Input5 /

hadoop fs -rm -r -f $OUTPUT_DIRECTORY
#hadoop jar $STREAMJAR  -mapper cat -reducer cat -input $INPUT -output $OUTPUT_DIRECTORY \
hadoop jar $STREAMJAR -files $MAPPER \
           -D stream.map.output.field.separator="\t" \
           -D stream.num.map.output.key.field=2 \
           -D num.key.fields.for.partition=1 \
           -D map.output.key.field.separator="\t" \
           -mapper $MAPPER \
           -reducer cat \
           -input $INPUT1 \
           -input $INPUT2 \
           -input $INPUT3 \
           -input $INPUT4 \
           -input $INPUT5 \
           -output $OUTPUT_DIRECTORY
hadoop fs -cat $OUTPUT_DIRECTORY/part* > $OUTPUT

