#!/bin/bash
 #===============================================================================
 #
 #          FILE:  ST_Reducer_s2_output 
 #
 #         USAGE:  ---
 #
 #   DESCRIPTION:  ---
 #
 #       OPTIONS:  ---
 #  REQUIREMENTS:  ---
 #          BUGS:  ---
 #         NOTES:  ---
 #        AUTHOR:  IC (Yin-Chi Peng), <psycsieic@gmail.com>
 #       COMPANY:  ---
 #       VERSION:  1.0
 #       CREATED:  2015-05-11 16:40:27
 #      REVISION:  ---
 #      MODIFIED:
 #
 #===============================================================================


STREAMJAR=/usr/local/hadoop/share/hadoop/tools/lib/hadoop-streaming-2.2.0.jar
INPUT=/mapper_s2_output
Small_Test_Input=./mapper_s2_output
OUTPUT=reducer_s2_output
OUTPUT_DIRECTORY=result

MAPPER=cat
REDUCER=reducer_s2
#REDUCER=""

#if [ $# -eq 1 ]
#then

hadoop fs -rm $INPUT

hadoop fs -put $Small_Test_Input /

hadoop fs -rm -r -f $OUTPUT_DIRECTORY
hadoop jar $STREAMJAR -files $REDUCER \
           -mapper $MAPPER \
           -reducer $REDUCER \
           -input $INPUT \
           -output $OUTPUT_DIRECTORY
hadoop fs -cat $OUTPUT_DIRECTORY/part* > $OUTPUT

#else
#echo "./s2_reducer_unit_test [search_target]"
#fi 
